//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOC.GSP.V2.WF.Engine.FunctionCallService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FunctionCallService.IFunctionCallService")]
    public interface IFunctionCallService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionCallService/CallFunction", ReplyAction="http://tempuri.org/IFunctionCallService/CallFunctionResponse")]
        string[] CallFunction(BOC.GSP.V2.WF.Common.Models.FunctionCallPara value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunctionCallService/CallFunction", ReplyAction="http://tempuri.org/IFunctionCallService/CallFunctionResponse")]
        System.Threading.Tasks.Task<string[]> CallFunctionAsync(BOC.GSP.V2.WF.Common.Models.FunctionCallPara value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFunctionCallServiceChannel : BOC.GSP.V2.WF.Engine.FunctionCallService.IFunctionCallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FunctionCallServiceClient : System.ServiceModel.ClientBase<BOC.GSP.V2.WF.Engine.FunctionCallService.IFunctionCallService>, BOC.GSP.V2.WF.Engine.FunctionCallService.IFunctionCallService {
        
        public FunctionCallServiceClient() {
        }
        
        public FunctionCallServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FunctionCallServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FunctionCallServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FunctionCallServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] CallFunction(BOC.GSP.V2.WF.Common.Models.FunctionCallPara value) {
            return base.Channel.CallFunction(value);
        }
        
        public System.Threading.Tasks.Task<string[]> CallFunctionAsync(BOC.GSP.V2.WF.Common.Models.FunctionCallPara value) {
            return base.Channel.CallFunctionAsync(value);
        }
    }
}
